# Generated by Django 5.0 on 2025-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20),
        ),
    ]
